### ISSUE TITLE
Simplification of code/attributes

### ISSUE THREAD

**Issue by Link2Twenty** [philipjkim/polymer-image-slider#3]
These are just a couple of ideas feel free to ignore them.

**polymer-image-slider.html#L86**
`<img id="image" src="{{currentImg}}" title$="{{currentImg}}">`
could this line be?
`<img id="image" src="{{images[currentPos]}}" title$="{{image[currentPos]}}">`

**polymer-image-slider.html#L116**
Rather than having an attribute you could use a custom CSS variable
Something like

``` CSS
#image {
  max-width: var(--image-slider-max-width, 400px);
  width: 100%;
}
```

Then the user could set `--image-slider-max-width` in their css and that would change the max width, though the default would be 400px
